### ISSUE TITLE
$fromPromise: promise rejects without a reason

### ISSUE THREAD

**Issue by charlierudolph** [Originate/nectarine#57]
If using `$fromPromise` and the promise rejects without a reason, there is no indication of that in the store. This is because `$setError` will be called with undefined. Couple possible improvements to make here:

* `$setError` throws if passed undefined
* `$fromPromise`: if the promise rejects without a reason, it calls `$setError()` with something like `new Error("Promise rejected without a reason")`

**Comment by alexdavid** [comment]
👍 I think both are good ideas
